UltimateForum.Razor/Pages/User/ChangePassword.cshtml.cs
using System.ComponentModel.DataAnnotations;
using AXHelper.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UltimateForum.Razor.Db;

namespace UltimateForum.Razor.Pages.User;

public class ChangePassword(ForumDbContext context) : PageModel
{
    private readonly ForumDbContext _db = context;
    public class PasswordChangeModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "此处不能为空")]
        public required string OldPassword { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "此处不能为空")]
        public required string NewPassword { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "此处不能为空")]
        [Compare(nameof(NewPassword), ErrorMessage = "确认密码必须一致")]
        public required string ConfirmPassword { get; set; }
    }
    [BindProperty]
    public PasswordChangeModel? PasswordChange { get; set; }
    public IActionResult OnGet()
    {
        if (HttpContext.Session.GetString("uid") is null)
        {
            return RedirectToPage("/Index");
            
        }
        return Page();
    }

    public IActionResult OnPostChangePassword()
    {
        if (!ModelState.IsValid) return BadRequest("输入不合法");
        _db.Users.Find(HttpContext.Session.GetLong("uid"))?.Password = PasswordChange?.NewPassword.ToSha256String() ?? throw new InvalidOperationException();
        _db.SaveChanges();
        HttpContext.Session.Remove("uid");
        return RedirectToPage("/Index");
    }
}

public static class SesisonExtension
{
    extension(ISession session)
    {
        public long? GetLong(string key)
        {
            return session.GetString(key) is null ? null :long.Parse(session.GetString(key)!);
        }
    }
}

UltimateForum.Razor/Pages/User/Home.cshtml.cs
using System.ComponentModel.DataAnnotations;
using AXHelper.Extensions;
using Ganss.Xss;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using UltimateForum.Razor.Db;

namespace UltimateForum.Razor.Pages.User;

[DisableRequestSizeLimit]
public class Home(ForumDbContext forumDbContext, BinaryDbContext binaryDbContext ): PageModel
{
    private readonly ForumDbContext _dbContext = forumDbContext;
    private readonly BinaryDbContext _binaryDbContext = binaryDbContext;

    
    public new UltimateForum.Db.Models.User User { get; set; } = null!;
    [BindProperty(SupportsGet = true)]
    public bool EditProfileFlag { get; set; }
    [BindProperty(SupportsGet = true)]
    public bool EditDescFlag { get; set; }

    public class EditProfileModel
    {
        public string? Email { get; set; }
    }
    [BindProperty]
    public EditProfileModel EditProfile { get; set; } = null!;

    public class AvatarUploadModel
    {
        [System.ComponentModel.DataAnnotations.Required]
        public IFormFile Profile { get; set; } = null!;
    }
    [BindProperty]
    public AvatarUploadModel AvatarUpload { get; set; } = null!;

    public class EditDescModel
    { 
        public string? Description { get; set; }
    }

    [BindProperty] 
    public EditDescModel EditDesc { get; set; } = null!;
    
    public IActionResult OnGet()
    {
        var u = _dbContext.Users.Include(i=>i.CreatedPosts).Include(i=>i.CreatedTopics).FirstOrDefault(i => i.Id == HttpContext.Session.GetLong("uid"));
        if (u is null)
        {
            return RedirectToPage("/Index");
        }
        
        User = u;
        if (EditProfileFlag)
        {
            EditProfile = new()
            {
                Email = User.Email
            };
        }
        return Page(); 
    }

    public IActionResult OnGetLogout()
    {
        HttpContext.Session.Remove("uid");
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostEditProfile()
    {
        _dbContext.Users.Where(i=>i.Id == HttpContext.Session.GetLong("uid")).ExecuteUpdate(i => i.SetProperty(u=>u.Email, EditProfile.Email));
        return RedirectToPage("/User/Home"); 
    }

    public IActionResult OnGetDeleteAccount()
    {
        var u = _dbContext.Users.Find(HttpContext.Session.GetLong("uid"));
        if (u is null)
        {
            return BadRequest(); 
        }
        _dbContext.Users.Remove(u);
        _dbContext.SaveChanges();
        HttpContext.Session.Remove("uid");
        return RedirectToPage("/Index");
    }
    public IActionResult OnPostUploadAvatar()
    {
        var original = _dbContext.Users.FirstOrDefault(i => i.Id == HttpContext.Session.GetLong("uid"))?.AvatarUuid;
        if (original is not null)
        {
            var oB = _binaryDbContext.Binaries.Find(original);
            if (oB is not null)
            {
                _binaryDbContext.Remove(oB);
            }
        }
        var guid = Guid.NewGuid().ToString();
        _binaryDbContext.Binaries.Add(new()
        {
            Uuid = guid, Content = AvatarUpload.Profile.ReadToByteArray()
        });
        _dbContext.Users.Find(HttpContext.Session.GetLong("uid"))?.AvatarUuid = guid; 
        _binaryDbContext.SaveChanges();
        _dbContext.SaveChanges();
        return RedirectToPage("/User/Home");
    }

    public IActionResult OnGetGetAvatar()
    {
        
        var c = _binaryDbContext.Binaries.Find(_dbContext.Users.FirstOrDefault(i=>i.Id == HttpContext.Session.GetLong("uid"))?.AvatarUuid)?.Content;
        if (c is null)
        {
            return NotFound(); 
        }
        return File(c, "image/webp");
    }

    public IActionResult OnPostEditDescHandler()
    {
        var sanitizer = new HtmlSanitizer(); 
        _dbContext.Users.Where(i => i.Id == HttpContext.Session.GetLong("uid"))
            .ExecuteUpdate(i => i.SetProperty(p => p.Description, EditDesc.Description is null ? null :sanitizer.Sanitize(EditDesc.Description)));
        return RedirectToPage("/User/Home");
    }
    
}

UltimateForum.Razor/Pages/User/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UltimateForum.Razor.Db;

namespace UltimateForum.Razor.Pages.User;

public class Login(ForumDbContext dbContext) : PageModel
{
    private readonly ForumDbContext _db = dbContext; 
    [BindProperty]
    [Required(AllowEmptyStrings = false, ErrorMessage = "用户名不可为空")]
    public required string Username { get; set; }
    [BindProperty]
    [Required(AllowEmptyStrings = false, ErrorMessage = "密码不可为空")]
    public required string Password { get; set; }
    
    [BindProperty(SupportsGet = true)]
    public string? WhereYouAreFrom { get; set; }
    public void OnGet()
    {
        Console.WriteLine(WhereYouAreFrom);
    }

    public IActionResult OnPostLogin()
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(); 
        }

        var user = _db.Users.FirstOrDefault(i => i.Username == Username);
        if (user is null)
        {
            ModelState.AddModelError("Username", "用户名或密码错误");
            return Page(); 
        }
        HttpContext.Session.SetString("uid", user.Id.ToString());
        return WhereYouAreFrom is null ?  RedirectToPage("/Index") : Redirect(WhereYouAreFrom); 
    }
}

UltimateForum.Razor/Pages/User/Register.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using AXHelper.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UltimateForum.Razor.Db;

namespace UltimateForum.Razor.Pages.User;

public class Register(ForumDbContext dbContext) : PageModel
{
    // TODO Register confirmation
    private readonly ForumDbContext _dbContext = dbContext;
    
    public class RegisterFormModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "用户名不可为空")]
        public required string Username { get; set; }    
        public string? Email { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "密码不可为空")]
        public required string Password { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "请确认密码")]
        [Compare(nameof(Password), ErrorMessage = "密码不一致")]
        public required string ConfirmPassword { get; set; }
    }
    [BindProperty]
    public RegisterFormModel? Form { get; set; }
    [BindProperty(SupportsGet = true)]
    public string? WhereYouAreFrom { get; set; }
    public void OnGet()
    {
        
    }

    public IActionResult OnPostRegister()
    {
        if (!ModelState.IsValid || Form is null)
        {
            ModelState.AddModelError("Username", "数据验证失败");
            return Page(); 
        }

        if (_dbContext.Users.Any(i => i.Username == Form.Username))
        {
            ModelState.AddModelError("Username", "用户名已存在");
            return Page();
        }
        try
        {
            
            _dbContext.Users.Add(new()
            {
                Username = Form.Username,
                Password = Form.Password.ToSha256String(),
                Joined = DateTime.Now,
                Email =  Form.Email,
                Op = false,
            });
            _dbContext.SaveChanges();
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            ModelState.AddModelError("Username", "服务器内部错误，请联系管理员");
            return Page(); 
        }

        var id = _dbContext.Users.FirstOrDefault(i => i.Username == Form.Username)?.Id;
        if (id is null)
        {
            ModelState.AddModelError("Username", "注册失败，请联系管理员");
            return Page(); 
        }
        HttpContext.Session.SetString("uid", id.Value.ToString());
        return WhereYouAreFrom is null ? RedirectToPage("/Index") : Redirect(WhereYouAreFrom);
    }
}

UltimateForum.Razor/Pages/User/ChangePassword.cshtml
@page "/User/ChangePassword"
@model UltimateForum.Razor.Pages.User.ChangePassword

<div class=" mx-auto  d-flex flex-column justify-content-center align-items-center col-6">
    <div class="w-100">
        <h1 class="display-4">更改密码</h1>
        <div class="card p-4 ">
            <form method="post">
                <div class="d-flex flex-column gap-3">
                    <span class="text-danger" asp-validation-for="@Model.PasswordChange!.OldPassword" ></span>
                    <input class="form-control" placeholder="旧密码" type="password" asp-for="@Model.PasswordChange!.OldPassword"/>
                    <span class="text-danger" asp-validation-for="@Model.PasswordChange!.NewPassword" ></span>
                    <input class="form-control" placeholder="新密码" type="password" asp-for="@Model.PasswordChange!.NewPassword"/>
                    <span class="text-danger" asp-validation-for="@Model.PasswordChange!.ConfirmPassword" ></span>
                    <input class="form-control" placeholder="确认新密码" type="password" asp-for="@Model.PasswordChange!.ConfirmPassword"/>
                    <button class="btn btn-primary" type="submit"  asp-page-handler="ChangePassword">更改</button>
                </div>

            </form>

        </div>
    </div>
    
</div>

<partial name="Validation"/>

UltimateForum.Razor/Pages/User/Home.cshtml
@page
@model UltimateForum.Razor.Pages.User.Home
@{
    ViewData["Title"] = Model.User.Username;
    
}


<div class="row gap-3">
    <div class="display-6">个人 - @Model.User.Username</div>
    <div class="card bg-light-subtle d-block w-100 p-3 px-5">
        <div class="mx-auto d-flex gap-3 align-items-center" style="max-width: 25rem">
            <div style="width: 5rem; height: 5rem;background-size: cover;background-position: center; background-image: url('@Url.Page(null, "GetAvatar")')" class="border bg-body-tertiary d-flex align-items-center" >
                <form method="post" id="avatar-form" asp-page-handler="UploadAvatar" enctype="multipart/form-data">
                    <input asp-for="AvatarUpload.Profile" oninput="(()=>{
                        document.getElementById('avatar-form-submit').click()
                    })()" type="file" class="form-control opacity-0 " style="zoom: 2"/>
                    <button type="submit" class="visually-hidden" id="avatar-form-submit"></button>
                </form>
            </div>
            <div>
                @if (Model.EditProfileFlag)
                {
                    <form method="post">
                        <div>用户名：@Model.User.Username</div>
                        <input class="form-control w-auto mt-2 form-control-sm" placeholder="Email（可选）" asp-for="EditProfile.Email"/>


                        <div class="d-flex flex-row gap-2 mt-2">
                            <button class="btn btn-primary btn-sm w-auto" asp-page-handler="EditProfile" type="submit">保存</button>
                            <a class="btn btn-danger btn-sm w-auto" asp-route-editProfileFlag="">取消</a>
                        </div>
                    </form>

                }
                else
                {
                    <div>用户名：@Model.User.Username</div>
                    <div>Email: @(Model.User.Email ?? "空")</div>


                    <div class="d-flex flex-row gap-2 mt-2">
                        <a class="btn btn-primary btn-sm w-auto" asp-route-editProfileFlag="true">更改</a>
                        <a class="btn btn-danger btn-sm w-auto" asp-page-handler="Logout">登出</a>
                        <a class="btn btn-danger btn-sm w-auto" asp-page-handler="DeleteAccount">删除账号</a>
                        <a class="btn btn-primary btn-sm w-auto" asp-page="/User/ChangePassword">更改密码</a>

                    </div>
                }
            </div>

        </div>
    </div>
    <div class="mt-1 card bg-light-subtle d-block w-100 pb-3 pt-2 px-5">
        <div class="row">
            <div class="col-6">
                <div>个人资料<hr class="my-2"/></div>
                @if (Model.EditDescFlag)
                {
                    <form method="post" asp-page-handler="EditDescHandler">
                        <textarea id="textarea-desc" class="form-control mb-2" asp-for="EditDesc.Description" style="min-height: 20rem">
                            
                        </textarea>
                        <script>
                            document.getElementById("textarea-desc").innerHTML = `@(Model.User.Description)`
                        </script>
                        <button type="submit" class="btn btn-primary btn-sm" >保存</button>
                    </form>
                }
                else
                {
                    <div style="font-size: .8rem">
                        @Html.Raw(Markdig.Markdown.ToHtml(string.IsNullOrWhiteSpace(Model.User.Description) ? "无" : Model.User.Description))
                        
                    </div>
                    <a class="btn btn-secondary btn-sm" asp-route-editDescFlag="true">更改</a>
                }
            </div>
            <div class="col-6">
                <div >统计<hr class="my-2"/></div>
                <div class="mx-auto" style="max-width: 25rem">
                    <div>加入时间：@Model.User.Joined</div>
                    <div>话题与回复数：@(Model.User.CreatedPosts.Count + Model.User.CreatedTopics.Count)</div>
                </div>
            </div>

        </div>
        
    </div>
</div>

UltimateForum.Razor/Pages/User/Login.cshtml
@page "/User/Login"
@model UltimateForum.Razor.Pages.User.Login


<div class=" mx-auto  d-flex flex-column justify-content-center align-items-center col-6">
    <div class="w-100">
        <h1 class="display-4">登录</h1>
        <div class="card p-4 ">
            <form method="post" asp-page-handler="Login" asp-route-whereyouarefrom="@Model.WhereYouAreFrom">
                <div class="d-flex flex-column gap-3">
                    <span class="text-danger" asp-validation-for="Username" ></span>
                    <input class="form-control" placeholder="用户名" asp-for="Username"/>
                    
                  
                    
                    <span class="text-danger" asp-validation-for="Password" ></span>
                    <input type="password" class="form-control" placeholder="密码" asp-for="Password"/>
                    
                   
                    <button class="btn btn-primary" type="submit">登录</button>
                </div>

            </form>

        </div>
    </div>
    
</div>

<partial name="Validation"/>

UltimateForum.Razor/Pages/User/Register.cshtml
@page
@model Register
<div class=" mx-auto  d-flex flex-column justify-content-center align-items-center col-6">
    <div class="w-100">
        <h1 class="display-4">注册</h1>
        <div class="card p-4 ">
            <form method="post">
                <div class="d-flex flex-column gap-3">
                    <span class="text-danger" asp-validation-for="Form!.Username" ></span>
                    <input class="form-control" placeholder="用户名" asp-for="Form!.Username"/>
                    
                    <span class="text-danger" asp-validation-for="Form!.Email" ></span>
                    <input type="email" class="form-control" placeholder="邮箱（可选）" asp-for="Form!.Email"/>
                    
                    <span class="text-danger" asp-validation-for="Form!.Password" ></span>
                    <input type="password" class="form-control" placeholder="密码" asp-for="Form!.Password"/>
                    
                    <span class="text-danger" asp-validation-for="Form!.ConfirmPassword" ></span>
                    <input type="password" class="form-control" placeholder="确认密码" asp-for="Form!.ConfirmPassword"/>
                    <button class="btn btn-primary" type="submit" asp-page-handler="Register" asp-route-whereyouarefrom="@Model.WhereYouAreFrom">注册</button>
                </div>

            </form>

        </div>
    </div>
    
</div>

<partial name="Validation"/>