UltimateForum.Razor/Pages/Board.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UltimateForum.Razor.Db;

namespace UltimateForum.Razor.Pages;

public class Board(ForumDbContext forumDbContext) : PageModel
{
    private readonly ForumDbContext _forumDbContext = forumDbContext;
    public Db.Models.Board BoardSpec = null!;
    [BindProperty(SupportsGet = true)]
    public long? BoardId { get; set; }
    public IActionResult OnGet()
    {
        if (!BoardId.HasValue)
        {
            return BadRequest();
        }

        if (_forumDbContext.Boards.FirstOrDefault(i => i.Id == BoardId) is null)
        {
            return RedirectToPage("/404");
        }
        BoardSpec = _forumDbContext.Boards.Include(i=>i.Topics).ThenInclude(i=>i.Posts.OrderByDescending(i=>i.CreatedAt)).ThenInclude(i=>i.Creator).FirstOrDefault(i => i.Id == BoardId) ?? throw new InvalidOperationException("This should not happen. ");
        return Page(); 
    }
}

UltimateForum.Razor/Pages/Dashboard.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UltimateForum.Razor.Db;
using UltimateForum.Razor.Pages.User;

namespace UltimateForum.Razor.Pages;

public class Dashboard(ForumDbContext db, AppConfiguration config) : PageModel
{ 
    [Required(AllowEmptyStrings = false, ErrorMessage = "请输入名称")]
    [BindProperty]
    public string? NewName { get; set; }
    
    [Required(AllowEmptyStrings = false, ErrorMessage = "请输入欢迎语")]
    [BindProperty]
    public string? ForumNameIndexWelcomePhrase { get; set; }
    
    [Required(AllowEmptyStrings = false, ErrorMessage = "请输入介绍文")]
    [BindProperty]
    public string? ForumDescription { get; set; }
    
    
    private readonly ForumDbContext _db = db ;
    public readonly AppConfiguration Config = config;
    public IActionResult OnGet()
    {
        if (HttpContext.Session.GetLong("uid") != 2)
        {
            return RedirectToPage("/index"); 
        }
        return Page();
    }

    public int TopicCount() => _db.Topics.Count();
    public int UserCount() => _db.Users.Count();
    public int PostCount() => _db.Posts.Count();

    public async Task<IActionResult> OnPostEditName()
    {
        if (ModelState.GetFieldValidationState("NewName") != ModelValidationState.Valid)
        {
            return BadRequest(); 
        }
        await Config.SetValueAsync("ForumName", NewName ?? throw new NullReferenceException());
        return RedirectToPage("/Dashboard"); 
    }

    public async Task<IActionResult> OnPostSaveIndexBlock()
    {
        if (ModelState.GetFieldValidationState("ForumNameIndexWelcomePhrase") != ModelValidationState.Valid)
        {
            return BadRequest(); 
        }

        if (ModelState.GetFieldValidationState("ForumDescription") != ModelValidationState.Valid)
        {
            return BadRequest(); 
        }
        await Config.SetValueAsync("ForumNameIndexWelcomePhrase",
            ForumNameIndexWelcomePhrase ?? throw new NullReferenceException());
        await Config.SetValueAsync("ForumDescription", ForumDescription ?? throw new NullReferenceException());
        return RedirectToPage("/Dashboard"); 
    }
    
    
}

UltimateForum.Razor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UltimateForum.Razor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

UltimateForum.Razor/Pages/Index.cshtml.cs
using System.ComponentModel.DataAnnotations;
using AXHelper.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using UltimateForum.Db;
using UltimateForum.Db.Models;
using UltimateForum.Razor.Db;
using UltimateForum.Razor.Db.Models;

namespace UltimateForum.Razor.Pages;

public class IndexModel(ForumDbContext context, BinaryDbContext binaryDbContext, IConfiguration configuration) : PageModel
{
    private readonly ForumDbContext _db = context;
    private readonly BinaryDbContext _binaryDbContext = binaryDbContext;
    public readonly IConfiguration Configuration = configuration;
    public List<Db.Models.Board> Boards = []; 

    
    [BindProperty]
        [Required(AllowEmptyStrings = false, ErrorMessage = "用户名为必填项")]
        public required string Username { get; set; }
    [BindProperty]
        
        [Required(AllowEmptyStrings = false, ErrorMessage = "密码为必填项")]
        public required string Password { get; set; }
    
    public IActionResult OnGet()
    {
        if (Configuration["AllowUserCreateBoard"] == "True")
        {
            Boards = _db.Boards
                .OrderByDescending(i => i.Created)
                .ToList();
        }
        else
        {
            Boards = _db.Boards
                .OrderBy(i => i.Order).ToList();
        }
        if(HttpContext.Session.GetString("uid") != null)
        {
            var u = _db.Users.FirstOrDefault(i=>i.Id == long.Parse(HttpContext.Session.GetString("uid") ?? string.Empty));
            if (u is null)
            {
                HttpContext.Session.Remove("uid");
                return RedirectToPage("/Index");
            }
            Username = u.Username; 
            
        }
        return Page();
    }

    public int GetTopicCount(long boardId)
    {
        return _db.Topics.Count(i => i.BoardId == boardId);
    }

    public int GetPostCount(long boardId)
    {
        return _db.Topics.Where(i=>i.BoardId == boardId).Include(i => i.Posts).Sum(i => i.Posts.Count);
    }

    public Post? GetLatestPost(long boardId)
    {
        return _db.Posts.Include(i=>i.Topic).Where(i=>i.Topic.BoardId == boardId).Include(i=>i.Creator).OrderByDescending(i=>i.CreatedAt).FirstOrDefault() ?? null;
    }
    public IActionResult OnPostLogin()
    {
        if (!ModelState.IsValid) return BadRequest("输入不合法");
       
      var u = _db.Users.FirstOrDefault(i=>i.Username == Username && i.Password == Password.ToSha256String());
      if (u == null)
      {
          ModelState.AddModelError( "Username", "用户名或密码错误");
          return OnGet(); 
      }

      HttpContext.Session.SetString("uid", u.Id.ToString());
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostLogout()
    {
        HttpContext.Session.Remove("uid");
        return RedirectToPage("/Index"); 
    }

    

    
}

UltimateForum.Razor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UltimateForum.Razor.Pages;

public class PrivacyModel : PageModel
{
    public void OnGet()
    {
    }
}

UltimateForum.Razor/Pages/Topic.cshtml.cs
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UltimateForum.Razor.Db;
using UltimateForum.Razor.Db.Models;

namespace UltimateForum.Razor.Pages;

public class Topic(ForumDbContext forumDbContext, BinaryDbContext binaryDbContext) : PageModel
{
    [BindProperty(SupportsGet = true)]
    public int? TopicId { get; set; }
 
    public Db.Models.Topic? TopicData { get; set; }
    private readonly ForumDbContext _db = forumDbContext;
    /// <summary>
    /// Use with caution.
    /// </summary>
    public ForumDbContext DbContext => _db; 
    private readonly BinaryDbContext _binaryDbContext = binaryDbContext;
    public IActionResult OnGet()
    {
        if (TopicId is null)
        {
            return RedirectToPage("/404");
        }
        var s = _db.Topics.Include(i=>i.Creater).Include(i=>i.Board).Include(i=>i.Posts.OrderBy(i=>i.CreatedAt)).ThenInclude(i=>i.Creator).FirstOrDefault(i => i.Id == TopicId);
        if (s is null)
        {
            return RedirectToPage("/404"); 
        }
        TopicData = s;
        return Page(); 
    }

    public IActionResult OnGetAvatar(long? userUid)
    {
        var a = _db.Users.FirstOrDefault(i => i.Id == userUid)?.AvatarUuid;
        if (a is null)
        {
            return NotFound(); 
        }

        var b = _binaryDbContext.Binaries.Find(a);
        if (b is null)
        {
            return NotFound(); 
        }

        return File(b.Content, "image/webp"); 

    }

    public string? Username(long? userUid)
    {
        return _db.Users.FirstOrDefault(i => i.Id == userUid)?.Username; 
    }

    public Post? GetPost(long? postId)
    {
        if (postId is null)
        {
            return null; 
        }

        return _db.Posts.FirstOrDefault(i => i.Id == postId);
    }
}

UltimateForum.Razor/Pages/WritePost.cshtml.cs
using System.ComponentModel.DataAnnotations;
using AXHelper.Extensions;
using Ganss.Xss;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UltimateForum.Razor.Db;
using UltimateForum.Razor.Db.Models;
using UltimateForum.Razor.Pages.User;

namespace UltimateForum.Razor.Pages;

public class WritePost(ForumDbContext db, IConfiguration config, OpenMojiIconPackHelperService iconPackHelperService) : PageModel
{
    private readonly ForumDbContext _db = db;
    public readonly OpenMojiIconPackHelperService IconPackHelperService = iconPackHelperService;
    /// <summary>
    /// Use with caution. 
    /// </summary>
    public ForumDbContext Db => _db;
    private readonly IConfiguration _config = config;
    [BindProperty(SupportsGet = true)]
    public long? TopicId { get; set; }
    public Db.Models.Topic? TopicData { get; set; }

    [BindProperty]
    [Required(AllowEmptyStrings = false, ErrorMessage = "标题不能为空")]
    public string Title { get; set; } = "";
    [BindProperty]
    [Required(AllowEmptyStrings =  false, ErrorMessage = "此项不为空")]
    public new string Content { get; set; } = "";
    [BindProperty]
    public string[] AttachmentUuid { get; set; } = [];

    public IActionResult OnGet()
    {
        if (TopicId is null)
        {
            return RedirectToPage("/Index"); 
        }

        if (!_db.Topics.Any(i => i.Id == TopicId))
        {
            return RedirectToPage("/Index");
        }
    
        if (_config["AllowAnonymousPost"] != "True" && !_db.Users.Any(i => i.Id == HttpContext.Session.GetLong("uid")))
        {
            return RedirectToPage("/User/Login", new{WhereYouAreFrom=HttpContext.Request.Path + "?topicid="+TopicId}); 
        }
        TopicData = _db.Topics.Include(i=>i.Creater).Include(i=>i.Posts).ThenInclude(i=>i.Creator).First(i => i.Id == TopicId);
        return Page(); 
    }

    public IActionResult OnPostPostPost()
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(); 
        }
        #region UserRetrieve

        var u = _db.Users.Find(HttpContext.Session.GetLong("uid"));
        
        if (u is null && _config["AllowAnonymousPost"] != "True")
        {
            return BadRequest("Anonymous post is not allowed.");
        }

        #endregion

        var firstOrDefault = _db.Topics.FirstOrDefault(i=>i.Id == TopicId);
        var sanitizer = new HtmlSanitizer();
        sanitizer.AllowedSchemes.Add("mailto");
        sanitizer.AllowedAttributes.Add("class");

        // var content = Content; 
        var content = sanitizer.Sanitize(Content); 
        if (string.IsNullOrWhiteSpace(content))
        {
            return RedirectToPage("/Topic", new { TopicId });
        }
       
        _db.Posts.Add(new()
        {
            Title = Title,
            Content =content,
            Topic = firstOrDefault ?? throw new InvalidOperationException(),
            AttachmentUuid = [], CreatedAt = DateTime.Now, Creator = u ?? _db.Users.Find((long)1)!
        });
        _db.SaveChanges();
        return RedirectToPage("/Topic", new{TopicId});
    }
}

UltimateForum.Razor/Pages/WriteTopic.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Ganss.Xss;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UltimateForum.Razor.Db;
using UltimateForum.Razor.Pages.User;

namespace UltimateForum.Razor.Pages;

public class WriteTopic(ForumDbContext forumDbContext, IConfiguration configuration) : PageModel
{
    public readonly IConfiguration Configuration = configuration;
    private readonly ForumDbContext _forumDbContext = forumDbContext;
    [BindProperty(SupportsGet = true)]
    [Required]
    public required long BoardId { get; set; }
    
    [BindProperty]
    [Required(AllowEmptyStrings = false, ErrorMessage = "标题不可为空")]
    public required string Title { get; set; }
    [BindProperty]
    [Required(AllowEmptyStrings = false, ErrorMessage = "内容不可为空")]
    public new required string Content { get; set; }
    
    public IActionResult OnGet()
    {
        if (BoardId is 0 || _forumDbContext.Boards.Find(BoardId) is null)
        {
            return RedirectToPage("/Index");
        }
        
        if (Configuration["AllowAnonymousTopic"]?.ToLowerInvariant() != "true" && (HttpContext.Session.GetLong("uid") is null || _forumDbContext.Users.Any(i=>i.Id == HttpContext.Session.GetLong("uid"))))
        {
            return RedirectToPage("/User/Login");
        }

        return Page(); 
    }

    public IActionResult OnPostPostTopic()
    {
        var board = _forumDbContext.Boards.Find(BoardId);
        if (board is null)
        {
            return BadRequest(); 
        }
        if (!ModelState.IsValid)
        {
            return BadRequest(); 
        }

        var user = _forumDbContext.Users.Find(HttpContext.Session.GetLong("uid")); 
        if (Configuration["AllowAnonymousTopic"]?.ToLowerInvariant() != "true" && user is null)
        {
            return BadRequest(); 
        }

        var sanitizer = new HtmlSanitizer();
        sanitizer.AllowedTags.Add("class"); 
        
        var topic = new Db.Models.Topic
        {
            Title = Title,
            Content = sanitizer.Sanitize(Content),
            Creater = user ?? _forumDbContext.Users.Find(1L),
            CreatedOn = DateTime.Now,
            Board = board 
        }; 
        _forumDbContext.Topics.Add(topic);
        _forumDbContext.SaveChanges();
        
        return RedirectToPage("/Topic", new { TopicId = topic.Id });
    }
}

UltimateForum.Razor/Pages/Board.cshtml
@page
@using UltimateForum.Razor.Db.Models
@model UltimateForum.Razor.Pages.Board
@{
    ViewData["Title"] = Model.BoardSpec.Name + "板块";
}
@section NavView
{
    <a asp-page="/Index" id="index" class="me-2">首页</a>
    /
    <a class="ms-2 me-2" id="board" asp-page="/Board" asp-route-boardid="@Model.BoardId">@Model.BoardSpec?.Name</a>
    }

    <div class="mb-3">
        <a asp-page="/Index" >@{ var e = "<==";<span>@e</span>} 主页</a>
    </div>
    <div class="mb-3">
        <a class="btn btn-primary btn-sm" asp-page="/WriteTopic" asp-route-boardid="@Model.BoardId">+新话题</a>
    </div>
<table class="table table-bordered">
    <thead>
    <tr>
        <td >
            话题
        </td>
        <td class="col-1">
            回复
        </td>
        <td class="col-2">
            最新回复
        </td>
    </tr>
    </thead>
    <tbody style="font-size: .9rem">
    @foreach (var boardSpecTopic in Model.BoardSpec.Topics)
    {
        <tr>
            <td >
                <a style="font-size: 1.25rem" asp-page="/Topic" asp-route-topicId="@boardSpecTopic.Id">@boardSpecTopic.Title</a>
                <div>By: <a asp-page="/">@(boardSpecTopic.Creater?.Username ?? "匿名或已删除")</a> >> @boardSpecTopic.CreatedOn</div>
                
            </td>
            <td class="text-center">
                @boardSpecTopic.Posts.Count
            </td>
            <td >
                @if (boardSpecTopic.Posts.OrderByDescending(i=>i.CreatedAt).FirstOrDefault() is { } post)
                {
                    <div>
                        By:@(post.Creator?.Username ?? "匿名或已删除") <a asp-page="/Topic" asp-route-topicId="@boardSpecTopic.Id" asp-fragment="@post.Id">前往</a>
                    </div>
                    <div class="text-secondary-emphasis">
                        @@@post.CreatedAt
                    </div>
                }
                else
                {
                    <div>版块为空</div>
                }
                
            </td>
        </tr>
    }
    </tbody>
</table>

UltimateForum.Razor/Pages/Dashboard.cshtml
@page
@model UltimateForum.Razor.Pages.Dashboard
@{ ViewData["Title"] = "设置页";}

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 p-1 d-flex flex-column gap-2">
            <div class="card p-3 bg-dark-subtle">
                <h2 class="fw-lighter">基本信息</h2>
                <div>
                    <form method="post">
                        <img src="~/assets/forum.jpg" alt="forum-icon"/><br/>
                        <span asp-validation-for="@Model.NewName" class="text-danger mt-2"></span>
                        <div class="mt-2 d-flex flex-column gap-2">
                            <span style="font-weight: 1">网站名称：</span><input id="new-name" class="form-control m-0" value="@Model.Config["ForumName"]" asp-for="NewName"/>
                            <span style="font-weight: 1">已注册用户：@Model.UserCount()</span>
                            <span style="font-weight: 1">话题数：@Model.TopicCount()</span>
                            <span style="font-weight: 1">回复数：@Model.PostCount()</span>
                            <button class="btn btn-primary" asp-page-handler="EditName" type="submit">保存</button>

                        </div>
                        
                    </form>
                    
                </div>
            </div>
            <div class="card p-3 bg-dark-subtle">
                <div>
                    <h2 class="fw-lighter">主页</h2>
                    <form method="post">
                        <span asp-validation-for="@Model.ForumNameIndexWelcomePhrase" class="text-danger mt-2"></span>
                        <label for="forum-welcome-phrase">欢迎语</label>
                        <input id="forum-welcome-phrase" class="form-control" asp-for="ForumNameIndexWelcomePhrase" value="@Model.Config["ForumNameIndexWelcomePhrase"]"/>
                        <span asp-validation-for="@Model.ForumDescription" class="text-danger mt-2"></span>
                        <label for="forum-desc-input">介绍文</label>
                        <input id="forum-desc-input" class="form-control" asp-for="@Model.ForumDescription" value="@Model.Config["ForumDescription"]"/>
                        <button type="submit" class="btn btn-primary" asp-page-handler="SaveIndexBlock">保存</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-8 p-1 ">
            <div class="card p-3 bg-dark-subtle">dd</div>
        </div>
    </div>
</div>

<partial name="Validation"/>

UltimateForum.Razor/Pages/Index.cshtml
@page
@using System.Text.RegularExpressions
@using AXHelper.Extensions
@using UltimateForum.Razor.Pages.User
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div style="max-width: 60rem" class="row mx-auto gap-md-0 gap-4">
    <div class="col-md-8 d-flex flex-column justify-content-center ">
        
        <h1 class="display-5 m-0">@{
                                      var temp = Model.Configuration["ForumNameIndexWelcomePhrase"];
                                      if (temp is null)
                                      {
                                          <span></span>
                                          return; 
                                      }

                                      var cs = Model.Configuration.AsEnumerable();
                                      var res= Helper.GenericTemplateReplace(temp, "\\{\\{(.*?)\\}\\}", replacements: cs.Select(i => (i.Key, i.Value!)).ToArray());
                                      <span>@res</span>
                                  }</h1>
        <div>@Model.Configuration["ForumDescription"]</div>
    </div>
    <div class="col-md-4">
        @if (HttpContext.Session.GetString("uid") is null)
        {
            <form id="login-form" method="post">
                <div class="card p-4 d-flex gap-2">
                    <span class="text-danger" asp-validation-for="@Model.Username" ></span>
                    <input placeholder="用户名" class="form-control" asp-for="@Model.Username"/>
                    <div asp-validation-summary="ModelOnly"></div>
                    <span class="text-danger" asp-validation-for="@Model.Password" ></span>
                    <input placeholder="密码" class="form-control"  asp-for="@Model.Password" type="password"/>
                    <div class="d-flex flex-row gap-1">
                        <button class="flex-grow-1 btn btn-primary" type="submit"  asp-page-handler="Login">登录</button>
                        <a class="flex-grow-1 btn btn-secondary" asp-page="/User/Register" id="index-register-button">注册...</a>
                    </div>
                </div>
            </form>
        }
        else
        {
            <div class="card p-4 d-flex gap-2">
                <h4>您已登录</h4>
                <div>欢迎回来，@Model.Username！</div>
                <form method="post">
                    <div class="d-flex flex-row gap-2">
                        <button class="btn btn-danger" type="submit" asp-page-handler="Logout">登出</button>
                        <a class="btn btn-primary"  asp-page="/User/Home">个人页</a>
                        @if (HttpContext.Session.GetLong("uid") == 2)
                        {
                            <a class="btn btn-primary" asp-page="/Dashboard">配置</a>
                        } 
                    </div> 
                    
                </form>
            </div>
        }
            

       
    </div>
</div>
<div style="max-width: 60rem" class="row mt-4 mx-auto">
    <table class="table table-bordered" id="boards">
        <thead >
        <tr>
            <td class="col-8">
                <div class="d-flex flex-row justify-content-between">
                    <span>板块</span>
                </div>
            </td>
            <td class="col-1 d-none d-md-table-cell">
                贴子
            </td>
            <td class="col-1 d-none d-md-table-cell">
                回复
            </td>
            <td class="d-none d-sm-table-cell">
                最新回复
            </td>
        </tr>
        </thead>
        <tbody>
        @foreach (Db.Models.Board b in Model.Boards)
        {
            <tr>
                <td>
                    <div >
                        <h5><a asp-page="/Board" asp-route-boardid="@b.Id">@b.Name</a></h5>
                        <div style="font-size: .7rem">@b.Description</div>
                    </div>
                   
                </td>
                <td class="text-center d-none d-md-table-cell">
                    <span>@Model.GetTopicCount(b.Id)</span>
                </td>
                <td class="text-center d-none d-md-table-cell">
                    <span>@Model.GetPostCount(b.Id)</span>
                </td>
                <td class="d-none d-sm-table-cell">
                    <span>
                        @{
                            var latest = Model.GetLatestPost(b.Id);
                            if (latest is null)
                            {
                                <span>板块中无话题</span>
                                
                            }
                            else
                            {
                                <div style="font-size: 12px">
                                    <div><a asp-page="/Topic" asp-route-TopicId="@latest.TopicId" asp-fragment="@latest.Id">Re: <strong >@latest.Topic.Title</strong></a></div>
                                    <div>By: <strong>@(latest.Creator?.Username ?? "匿名")</strong></div>
                                    <div class="text-secondary-emphasis">@latest.Content.ConcatEllipsisByChar(6)</div>
                                </div>
                                
                            }
                        }
                        
                    </span>
                </td>
            </tr>
        }
        
        </tbody>
    </table>
</div>
<script>
    document.getElementById('index-register-button').href += "?whereyouarefrom=" + encodeURIComponent(location.href);
</script>
<partial name="Validation"/>

UltimateForum.Razor/Pages/WriteTopic.cshtml
@page
@model UltimateForum.Razor.Pages.WriteTopic

<partial name="Validation"/>
<script src="https://cdn.jsdelivr.net/npm/marked/lib/marked.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked-highlight/lib/index.umd.js"></script>
<link rel="stylesheet" href="~/lib/highlight.js/styles/base16/windows-95.css">
<script src="~/lib/highlight.js/highlight.min.js"></script>
<script src="~/lib/monaco-editor/min/vs/loader.js" ></script>

@* ReSharper disable once Html.PathError *@
<script >
    const { Marked } = globalThis.marked;
    const { markedHighlight } = globalThis.markedHighlight;
    let editorDoc = null;
    let parseFunc = null;
    function Init(parse){
        parseFunc = parse;
    }
    function CalledOnInput(){
        document.getElementById('rendered').innerHTML = parseFunc(editorDoc.getValue());
        document.getElementById('text-hidden').value = parseFunc(editorDoc.getValue());
    }
    require.config({ paths: { 'vs': '@Url.Content("~/lib/monaco-editor/min/vs")' } });
    require(['vs/editor/editor.main'], function () {
        editorDoc = monaco.editor.create(document.getElementById('editor'), {
            value: [
                'function hello() {',
                '\tconsole.log("Hello world!");',
                '}'
            ].join('\n'),
            language: 'markdown',
            theme: 'vs-dark',
            automaticLayout: true // Resizes if the container changes
        });
        
        console.log(editorDoc.getValue())
        editorDoc.setValue("");
      
        
        const markedCustom = new Marked(
            markedHighlight({
                emptyLangClass: 'hljs',
                langPrefix: 'hljs language-',
                highlight(code, lang){
                    const language = hljs.getLanguage(lang) ? lang : 'plaintext';
                    return hljs.highlight(code, { language }).value;
                }
            })

        )
        Init(markedCustom.parse)
        
        editorDoc.onDidChangeModelContent(()=>{
            console.log(editorDoc.getValue());
            CalledOnInput();
        }) 
    });
    
    
</script>

<div class="display-6">发布话题</div>
<div class="card bg-dark-subtle mt-2 p-3" id="rendered" style="min-height: 15rem;">

</div>
<form method="post" asp-page-handler="PostTopic" asp-route-boardid="@Model.BoardId">
    <span asp-validation-for="@Model.Title" class="text-danger mt-2"></span>
    <input placeholder="标题" asp-for="@Model.Title" class="form-control mt-2" value="默认标题"></input>
    <span asp-validation-for="@Model.Content" class="text-danger mt-2"></span>
    <textarea style="height: 0;display: flex" class="opacity-0" asp-for="@Model.Content" id="text-hidden"></textarea>
    <div style="height: 15rem" class=" mt-2"  id="editor"></div>
    <button class="btn btn-primary btn-sm mt-2" type="submit">发送</button>
</form>